### ISSUE TITLE
isDirty flag always true after save

### ISSUE THREAD

**Issue by fsmanuel** [locks/ember-localstorage-adapter#100]
Does anyone know why the `isDirty` flag is always true after `save()`?

**Comment by kurko** [comment]
Is this something happening only with LS adapter? Seems like an Ember bug.

**Comment by fsmanuel** [comment]
That might be the case. I'll check with the RESTAdapter.

**Comment by fsmanuel** [comment]
i tried with the RESTAdapter and it sets the `isDirty` flag correctly.

**Comment by kurko** [comment]
I'm afraid I don't know how to help. I'd need more info. Maybe a failing test or a demo app?

**Comment by locks** [comment]
To echo the previous message, without a reproduction of the bug I am helpless to fix this.
If you still encounter this problem and can provide more issue feel free to reopen the issue for discussion.
