### ISSUE TITLE
calling find for a non-existent id leaves record permanently in Loading state

### ISSUE THREAD

**Issue by lastobelus** [locks/ember-localstorage-adapter#12]
I believe it should transition to Error?

**Comment by locks** [comment]
Does this still apply? cc @genkgo

**Comment by lastobelus** [comment]
@locks I'm not sure. I'm not actively working on any Ember projects ATM.

**Comment by locks** [comment]
I'll close it due to https://github.com/locks/ember-localstorage-adapter/issues/12#issuecomment-45630959 and old age. Let's assume it works because Data fixed their bug.
Thank you for the feedback @lastobelus!
