### ISSUE TITLE
store.find('model-type', { prop: value} ) no longer working in 0.5.4

### ISSUE THREAD

**Issue by Kilowhisky** [locks/ember-localstorage-adapter#123]
Since 0.5.4 i can no longer recover models using find or findQuery.

**Comment by Kilowhisky** [comment]
I think i found the problem. 

`DS.hasMany('model')` relationships are failing because of this line change in the last commit.

```
-        var foreignAdapter = type.store.adapterFor(relationModel);
+        var foreignAdapter = store.adapterFor(relationName);
```

`type.store.adapterFor(relationModel);` does not throw any deprecations so why was it switched out? 

FYI `store.adapterFor(relationName)` also works without exploding.

**Comment by srsgores** [comment]
I may be experiencing a related bug.  After upgrading to ``0.5.4``, I get an error when retrieving a record with ``store.find(modelName, id)``, resulting in the following error:

> Error while processing route: No model was found for ``coApplicants``

Where ``coApplicants`` is a ``hasMany`` relationship on a given model (not ``async``)

**Comment by kurko** [comment]
What versions of Ember Data are you using?

**Comment by srsgores** [comment]
1.18 beta

**Comment by duizendnegen** [comment]
This is affecting my solution as well - I thought it had to do with pluralization, but no

**Comment by patuku-roy** [comment]
I'm facing the same problem, any luck? or maybe any updates about this issue @Kilowhisky @srsgores @kurko @duizendnegen ? I really need this fix because I need to query based on several columns using findQuery, I hope new commit will release soon if not available yet.

**Comment by locks** [comment]
#124 says it fixes this, please reopen if that's not the case.
