### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by sescobb27** [locks/ember-localstorage-adapter#133]
Hi, I was wondering when are you planning to make a new release? we are running Ember Data 1.13.x and Ember 1.13.x and we are having this warnings:
`Adapter#find has been deprecated  and renamed to 'findRecord'.`
`Ember.keys is deprecated in favor of Object.keys`
But as I can see in your master branch you already fix those things. So I'm wondering when is the next release out? thanks

**Comment by locks** [comment]
I'll try to cut a patch version release tomorrow, thanks for bringing it up.

**Comment by kurko** [comment]
@locks let me know if there's anything I can do to help you :)

**Comment by locks** [comment]
:fire: https://www.npmjs.com/package/ember-localstorage-adapter :fire:
