### ISSUE TITLE
Ember data 2.3+ does not work with this addon

### ISSUE THREAD

**Issue by Kilowhisky** [locks/ember-localstorage-adapter#140]
It seems they've messed with the namespaces for ember data 2.3+. It may no longer be possible to extend the local storage adapter off of the DS namespace.

**Comment by bmac** [comment]
My guess is the issue here is the fact that `DS` is no longer a global variable when using Ember Data as an Ember CLI addon. @Kilowhisky if you add `"ember-data": "2.3.0" to `bower.json` does this addon start working again?

**Comment by oliverwilkie** [comment]
@bmac I can confirm that a short term of adding "ember-data": "2.3.0" makes this addon start working again.

What would be the long term way to solve this?

**Comment by bmac** [comment]
Long term `ember-localstorage-adapter` will likely need to implement a pattern similar to this: https://github.com/pangratz/ember-test-helpers/blob/dad6aed9cd84c98861a125dff501378b93693752/lib/ember-test-helpers/build-registry.js#L100-L110 

To attempt to load the `Adapter` and `JSONSerializer` out of the require context instead of assuming DS is a global on the page.

**Comment by Kilowhisky** [comment]
Really this addon should be rebuilt as an actuall ember-cli addon. Probably not too hard to rip the script apart and put it into module form.  Then again i'm not entirely sure of the future of this repo.

**Comment by B-Stefan** [comment]
Actually, I work the transformation into an ember-cli-addon. Most of the work is done but I have some trouble with the integration of the old tests into the new ember-cli-addon test context. I'm not really sure how to handle the old tests. Any idea ? 

Should we create a separate issue for this ? 

My code is available at https://github.com/b-stefan/ember-localstorage-adapter.git#ember-cli-addon

**Comment by Kilowhisky** [comment]
I think that if this repo does become a proper addon it'll need to abide by the 
```
import LSSerializer from 'ember-local-storage/serializers/serializer;
```
syntax by default and maybe have a shim that inserts it into `DS.LSSerializer` when DS is detected on the global scope.

**Comment by locks** [comment]
Making LSA a proper addon is my goal, but I've been way more busy than I thought I'd be. I wasn't sure how to handle the tests either :P

I will release a 2.x LSA addon in the future, not retro-compatible. I am studying how best to provide a 1.x release with globals support.

**Comment by Kilowhisky** [comment]
Another option is to talk with the guy making this addon

https://github.com/funkensturm/ember-local-storage

And maybe talk about a merger?

**Comment by DanielOchoa** [comment]
Would you accept a PR that makes it into a proper addon for 2.x? This, of course, would include tests.

**Comment by locks** [comment]
@DanielOchoa I would, but preferably if you coordinate with me in Slack/IRC so I don't have to review the entire process in one sitting.

**Comment by DanielOchoa** [comment]
Sounds reasonable enough. I'll probably hit you up in slack in the following days.

**Comment by locks** [comment]
Much appreciated! Talk to you soon.

**Comment by Kilowhisky** [comment]
Yay! :+1:  :heart_eyes:

**Comment by DanielOchoa** [comment]
https://github.com/locks/ember-localstorage-adapter/pull/141

**Comment by locks** [comment]
RC1 is out, can you peeps try it out?

**Comment by DanielOchoa** [comment]
Sure thing

**Comment by Kilowhisky** [comment]
Looking good in my app! 

I was able to remove the "ember-data" from my `bower.json` too.

**Comment by oliw** [comment]
Same, many thanks!

**Comment by DanielOchoa** [comment]
It works as expected on the application I'm using it at.

**Comment by SmileyJames** [comment]
Looking good for me, much appreciated Daniel.

**Comment by locks** [comment]
Thanks for the feedback :)
