### ISSUE TITLE
deleting record(removing association)  from hasMany relationship array  not persisting(getting saved) on localstorage.

### ISSUE THREAD

**Issue by oblongta** [locks/ember-localstorage-adapter#40]
on deleting a record from hasMany relationship array ,the records get deleted However it is not persisted (saved) on localstorage.As,as a result on reload,view is rendered with deleted record also.

I am using ember-data-beta-6 and latest version of local storage adapter.
Here is snippet of code:

App.EmployeesController=Ember.ArrayController.extend({
delete:function(record){
var a=this.get('model');
a.removeObject(record);
a.save();
}
});

My model is hasMany relationship array and record is the object to be removed from that array.

**Comment by locks** [comment]
I also believe this to be an Ember Data problem and thus not specific to LSA.
