### ISSUE TITLE
Relation deserialization should not use field name to infer model type

### ISSUE THREAD

**Issue by orospakr** [locks/ember-localstorage-adapter#51]
I'm using Ember Data 1.0beta7.  ELA is 2af84dee8eb6bbcfdc62e0d4b4613ec113445916 (current master as of writing).  I'm using EAK and the transpiler if that matters at all.

I've noticed that `extractSingle()` seems to use the field name to guess what the type of the relation is.  However, in ED, the type of the relation is intended specified to the `hasMany()` helper itself, not inferred from the field name (afaict).  This supports the case of having multiple relations of the same type, for instance.

The error manifests as "No model was found for _$fieldname_".

**Comment by locks** [comment]
Closing issue according to previous comment.
