### ISSUE TITLE
Not working with Ember-CLI with instructions from README

### ISSUE THREAD

**Issue by micahblu** [locks/ember-localstorage-adapter#84]
I installed as instructed: `bower install --save-dev ember-localstorage-adapter`

and have this in adapters/application.js:

``` js
import DS from 'ember-data';

export default DS.LSAdapter.extend({
    namespace: 'todoapp'
});
```

Wouldn't I also need to import the localstorage adapter somehow? I tried to import it from the bower directory but still no luck

This is the error I have:
`Error while processing route: todos.index Cannot read property 'extend' of undefined TypeError: Cannot read property 'extend' of undefined`

**Comment by dzena** [comment]
Hello,
i have followed the instruction for setting up the adapter from ember-cli (http://stackoverflow.com/questions/24327090/how-to-import-module-ember-localstorage-adapter-with-ember-cli). 
Unfortunately, i'm stuck at the 
Error message: " Error while processing route: products.index Cannot read property 'extend' of undefined TypeError: Cannot read property 'extend' of undefined".

I'll be happy with any help somebody can provide.
Regards

**Comment by dzena** [comment]
I solved the problem. 
Sorry for false alarm.

All I had to do is to restart the ember server.

Best regards.

**Comment by kurko** [comment]
:smile:

**Comment by planetcrypton** [comment]
I'm stuck here with the same symptoms:
Ran: $ ember install:bower ember-localstorage-adapter
app/adapters/application.js:
```javascript
import DS from 'ember-data';

// export default DS.FixtureAdapter.extend({});
export default DS.LSAdapter.extend({
    namespace: 'tapp2'
});
```

These are my versions:
DEBUG: -------------------------------
ember.debug.js:5197DEBUG: Ember      : 1.11.1
ember.debug.js:5197DEBUG: Ember Data : 1.0.0-beta.16.1
ember.debug.js:5197DEBUG: jQuery     : 1.11.2
ember.debug.js:5197DEBUG: -------------------------------

What exactly would I need to do in the Brocfile.js, that isn't very clear to me?

**Comment by scambier** [comment]
Before the last line:

`app.import('bower_components/ember-localstorage-adapter/localstorage_adapter.js');`

**Comment by planetcrypton** [comment]
I just had this working, when my code-buddy pointed out for me that I should run this in stead:

$ ember install ember-localstorage-adapter 

That made it work.
