### ISSUE TITLE
ember-addon-main is deprecated

### ISSUE THREAD

**Issue by borisrorsvort** [locks/ember-localstorage-adapter#87]
would be nice to update to the new structure.
https://github.com/search?q=deprecated+ember-addon-main+definition&type=Code&utf8=%E2%9C%93

**Comment by kurko** [comment]
@borisrorsvort ![](https://cloud.githubusercontent.com/assets/39081/4631743/a5b7b010-53b7-11e4-9fa8-cf10778cce26.png) seems to be how LS is designed to store the content. It uses the `id` as a key so it's easier to fetch it once it's there.

**Comment by locks** [comment]
I'm closing this issue because the original problem doesn't seem to apply anymore.
